//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpDb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EmployeeDBEntities : DbContext
    {
        public EmployeeDBEntities()
            : base("name=EmployeeDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<EmployeeProjectMapping> EmployeeProjectMapping { get; set; }
        public virtual DbSet<Project> Project { get; set; }

        public System.Data.Entity.DbSet<EmpModels.EmployeeModel> EmployeeModels { get; set; }

        public System.Data.Entity.DbSet<EmpModels.EmployeeProjectMappingModel> EmployeeProjectMappingModels { get; set; }

        public System.Data.Entity.DbSet<EmpModels.ProjectModel> ProjectModels { get; set; }

        public System.Data.Entity.DbSet<EmpModels.DepartmentModel> DepartmentModels { get; set; }
    }
}
